
services:
  db:
    image: pgvector/pgvector:pg16 
    container_name: postgres_db
    environment:
      
      POSTGRES_DB: ${POSTGRES_DB:-mediasearch} 
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    ports:
      - "5433:5432" 
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    
    restart: unless-stopped 

  feature-extractor:
    build: ./python-feature-extraction
    container_name: feature_extractor_service
    environment:
      FEATURE_SERVER_ADDRESS: "0.0.0.0:50051" 
      DEVICE: "cuda" 
      PYTHONUNBUFFERED: 1
    runtime: nvidia 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 
              capabilities: [gpu]
    ports:
      - "50051:50051" 
    networks:
      - app_network
    depends_on:
      db: 
        condition: service_healthy 
    restart: unless-stopped

  scraper:
    build: ./python-web-scraper
    container_name: scraper_service
    environment:
      SCRAPE_SERVER_ADDRESS: "0.0.0.0:50052"
      GO_API_GRPC_ADDRESS: "go-api:50050" 
      PYTHONUNBUFFERED: 1
    ports:
      - "50052:50052" 
    networks:
      - app_network
    depends_on:
      - go-api 
    # restart: unless-stopped

  go-api:
    build: ./go-api-provider
    container_name: go_api_service
    environment:
      
      DB_HOST: db 
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER:-user}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-password}
      DB_NAME: ${POSTGRES_DB:-mediasearch}
      DB_SSL_MODE: "disable" 
      
      FEATURE_EXTRACTOR_ADDR: "feature-extractor:50051"
      SCRAPER_ADDR: "scraper:50052"
      
      HTTP_SERVER_PORT: "8080" 
      GRPC_SERVER_PORT: "50050"
      
    ports:
      - "8080:8080"   
      - "50050:50050"   
    networks:
      - app_network
    depends_on:
      db:
        condition: service_healthy
      feature-extractor: 
         condition: service_started 
    restart: unless-stopped
  
  frontend: 
    build: ./simple-front-end 
    container_name: frontend_ui
    ports:
      - "3000:80" 
    networks:
      - app_network
    depends_on:
      - go-api 
    restart: unless-stopped

volumes:
  postgres_data: 

networks:
  app_network:   
    driver: bridge 