// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: scrape.proto

package scrapepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_UNKNOWN  Status = 0
	Status_ACCEPTED Status = 1
	Status_REJECTED Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "ACCEPTED",
		2: "REJECTED",
	}
	Status_value = map[string]int32{
		"UNKNOWN":  0,
		"ACCEPTED": 1,
		"REJECTED": 2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_scrape_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_scrape_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_scrape_proto_rawDescGZIP(), []int{0}
}

type ScrapeJobState int32

const (
	ScrapeJobState_STATE_UNKNOWN ScrapeJobState = 0
	ScrapeJobState_PENDING       ScrapeJobState = 1
	ScrapeJobState_RUNNING       ScrapeJobState = 2
	ScrapeJobState_COMPLETED     ScrapeJobState = 3
	ScrapeJobState_FAILED        ScrapeJobState = 4
)

// Enum value maps for ScrapeJobState.
var (
	ScrapeJobState_name = map[int32]string{
		0: "STATE_UNKNOWN",
		1: "PENDING",
		2: "RUNNING",
		3: "COMPLETED",
		4: "FAILED",
	}
	ScrapeJobState_value = map[string]int32{
		"STATE_UNKNOWN": 0,
		"PENDING":       1,
		"RUNNING":       2,
		"COMPLETED":     3,
		"FAILED":        4,
	}
)

func (x ScrapeJobState) Enum() *ScrapeJobState {
	p := new(ScrapeJobState)
	*p = x
	return p
}

func (x ScrapeJobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScrapeJobState) Descriptor() protoreflect.EnumDescriptor {
	return file_scrape_proto_enumTypes[1].Descriptor()
}

func (ScrapeJobState) Type() protoreflect.EnumType {
	return &file_scrape_proto_enumTypes[1]
}

func (x ScrapeJobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScrapeJobState.Descriptor instead.
func (ScrapeJobState) EnumDescriptor() ([]byte, []int) {
	return file_scrape_proto_rawDescGZIP(), []int{1}
}

type StartScrapeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StartUrl       string                 `protobuf:"bytes,1,opt,name=start_url,json=startUrl,proto3" json:"start_url,omitempty"`
	AllowedDomains string                 `protobuf:"bytes,2,opt,name=allowed_domains,json=allowedDomains,proto3" json:"allowed_domains,omitempty"`
	DepthLimit     int32                  `protobuf:"varint,3,opt,name=depth_limit,json=depthLimit,proto3" json:"depth_limit,omitempty"`
	CrawlStrategy  string                 `protobuf:"bytes,4,opt,name=crawl_strategy,json=crawlStrategy,proto3" json:"crawl_strategy,omitempty"`
	UsePlaywright  bool                   `protobuf:"varint,5,opt,name=use_playwright,json=usePlaywright,proto3" json:"use_playwright,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartScrapeRequest) Reset() {
	*x = StartScrapeRequest{}
	mi := &file_scrape_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartScrapeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartScrapeRequest) ProtoMessage() {}

func (x *StartScrapeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scrape_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartScrapeRequest.ProtoReflect.Descriptor instead.
func (*StartScrapeRequest) Descriptor() ([]byte, []int) {
	return file_scrape_proto_rawDescGZIP(), []int{0}
}

func (x *StartScrapeRequest) GetStartUrl() string {
	if x != nil {
		return x.StartUrl
	}
	return ""
}

func (x *StartScrapeRequest) GetAllowedDomains() string {
	if x != nil {
		return x.AllowedDomains
	}
	return ""
}

func (x *StartScrapeRequest) GetDepthLimit() int32 {
	if x != nil {
		return x.DepthLimit
	}
	return 0
}

func (x *StartScrapeRequest) GetCrawlStrategy() string {
	if x != nil {
		return x.CrawlStrategy
	}
	return ""
}

func (x *StartScrapeRequest) GetUsePlaywright() bool {
	if x != nil {
		return x.UsePlaywright
	}
	return false
}

type StartScrapeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=scrape.Status" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartScrapeResponse) Reset() {
	*x = StartScrapeResponse{}
	mi := &file_scrape_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartScrapeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartScrapeResponse) ProtoMessage() {}

func (x *StartScrapeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scrape_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartScrapeResponse.ProtoReflect.Descriptor instead.
func (*StartScrapeResponse) Descriptor() ([]byte, []int) {
	return file_scrape_proto_rawDescGZIP(), []int{1}
}

func (x *StartScrapeResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StartScrapeResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNKNOWN
}

func (x *StartScrapeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ScrapeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeStatusRequest) Reset() {
	*x = ScrapeStatusRequest{}
	mi := &file_scrape_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeStatusRequest) ProtoMessage() {}

func (x *ScrapeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scrape_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeStatusRequest.ProtoReflect.Descriptor instead.
func (*ScrapeStatusRequest) Descriptor() ([]byte, []int) {
	return file_scrape_proto_rawDescGZIP(), []int{2}
}

func (x *ScrapeStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type ScrapeStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State         ScrapeJobState         `protobuf:"varint,2,opt,name=state,proto3,enum=scrape.ScrapeJobState" json:"state,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ItemsScraped  int32                  `protobuf:"varint,4,opt,name=items_scraped,json=itemsScraped,proto3" json:"items_scraped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeStatusResponse) Reset() {
	*x = ScrapeStatusResponse{}
	mi := &file_scrape_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeStatusResponse) ProtoMessage() {}

func (x *ScrapeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scrape_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeStatusResponse.ProtoReflect.Descriptor instead.
func (*ScrapeStatusResponse) Descriptor() ([]byte, []int) {
	return file_scrape_proto_rawDescGZIP(), []int{3}
}

func (x *ScrapeStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ScrapeStatusResponse) GetState() ScrapeJobState {
	if x != nil {
		return x.State
	}
	return ScrapeJobState_STATE_UNKNOWN
}

func (x *ScrapeStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ScrapeStatusResponse) GetItemsScraped() int32 {
	if x != nil {
		return x.ItemsScraped
	}
	return 0
}

var File_scrape_proto protoreflect.FileDescriptor

const file_scrape_proto_rawDesc = "" +
	"\n" +
	"\fscrape.proto\x12\x06scrape\"\xc9\x01\n" +
	"\x12StartScrapeRequest\x12\x1b\n" +
	"\tstart_url\x18\x01 \x01(\tR\bstartUrl\x12'\n" +
	"\x0fallowed_domains\x18\x02 \x01(\tR\x0eallowedDomains\x12\x1f\n" +
	"\vdepth_limit\x18\x03 \x01(\x05R\n" +
	"depthLimit\x12%\n" +
	"\x0ecrawl_strategy\x18\x04 \x01(\tR\rcrawlStrategy\x12%\n" +
	"\x0euse_playwright\x18\x05 \x01(\bR\rusePlaywright\"n\n" +
	"\x13StartScrapeResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12&\n" +
	"\x06status\x18\x02 \x01(\x0e2\x0e.scrape.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\",\n" +
	"\x13ScrapeStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x9a\x01\n" +
	"\x14ScrapeStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12,\n" +
	"\x05state\x18\x02 \x01(\x0e2\x16.scrape.ScrapeJobStateR\x05state\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12#\n" +
	"\ritems_scraped\x18\x04 \x01(\x05R\fitemsScraped*1\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bACCEPTED\x10\x01\x12\f\n" +
	"\bREJECTED\x10\x02*X\n" +
	"\x0eScrapeJobState\x12\x11\n" +
	"\rSTATE_UNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x042\xa6\x01\n" +
	"\x0eScraperService\x12F\n" +
	"\vStartScrape\x12\x1a.scrape.StartScrapeRequest\x1a\x1b.scrape.StartScrapeResponse\x12L\n" +
	"\x0fGetScrapeStatus\x12\x1b.scrape.ScrapeStatusRequest\x1a\x1c.scrape.ScrapeStatusResponseBQZOgithub.com/Mahmoud-T-Almetwally/Image-Audio-Web-Search/internal/client/scrapepbb\x06proto3"

var (
	file_scrape_proto_rawDescOnce sync.Once
	file_scrape_proto_rawDescData []byte
)

func file_scrape_proto_rawDescGZIP() []byte {
	file_scrape_proto_rawDescOnce.Do(func() {
		file_scrape_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scrape_proto_rawDesc), len(file_scrape_proto_rawDesc)))
	})
	return file_scrape_proto_rawDescData
}

var file_scrape_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_scrape_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_scrape_proto_goTypes = []any{
	(Status)(0),                  // 0: scrape.Status
	(ScrapeJobState)(0),          // 1: scrape.ScrapeJobState
	(*StartScrapeRequest)(nil),   // 2: scrape.StartScrapeRequest
	(*StartScrapeResponse)(nil),  // 3: scrape.StartScrapeResponse
	(*ScrapeStatusRequest)(nil),  // 4: scrape.ScrapeStatusRequest
	(*ScrapeStatusResponse)(nil), // 5: scrape.ScrapeStatusResponse
}
var file_scrape_proto_depIdxs = []int32{
	0, // 0: scrape.StartScrapeResponse.status:type_name -> scrape.Status
	1, // 1: scrape.ScrapeStatusResponse.state:type_name -> scrape.ScrapeJobState
	2, // 2: scrape.ScraperService.StartScrape:input_type -> scrape.StartScrapeRequest
	4, // 3: scrape.ScraperService.GetScrapeStatus:input_type -> scrape.ScrapeStatusRequest
	3, // 4: scrape.ScraperService.StartScrape:output_type -> scrape.StartScrapeResponse
	5, // 5: scrape.ScraperService.GetScrapeStatus:output_type -> scrape.ScrapeStatusResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_scrape_proto_init() }
func file_scrape_proto_init() {
	if File_scrape_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scrape_proto_rawDesc), len(file_scrape_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scrape_proto_goTypes,
		DependencyIndexes: file_scrape_proto_depIdxs,
		EnumInfos:         file_scrape_proto_enumTypes,
		MessageInfos:      file_scrape_proto_msgTypes,
	}.Build()
	File_scrape_proto = out.File
	file_scrape_proto_goTypes = nil
	file_scrape_proto_depIdxs = nil
}
