// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: indexing.proto

package indexingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaType int32

const (
	MediaType_UNKNOWN MediaType = 0
	MediaType_IMAGE   MediaType = 1
	MediaType_AUDIO   MediaType = 2
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "UNKNOWN",
		1: "IMAGE",
		2: "AUDIO",
	}
	MediaType_value = map[string]int32{
		"UNKNOWN": 0,
		"IMAGE":   1,
		"AUDIO":   2,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_indexing_proto_enumTypes[0].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_indexing_proto_enumTypes[0]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_indexing_proto_rawDescGZIP(), []int{0}
}

type ScrapedItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageUrl       string                 `protobuf:"bytes,1,opt,name=page_url,json=pageUrl,proto3" json:"page_url,omitempty"`
	MediaUrl      string                 `protobuf:"bytes,2,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	MediaType     MediaType              `protobuf:"varint,3,opt,name=media_type,json=mediaType,proto3,enum=indexing.MediaType" json:"media_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapedItem) Reset() {
	*x = ScrapedItem{}
	mi := &file_indexing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapedItem) ProtoMessage() {}

func (x *ScrapedItem) ProtoReflect() protoreflect.Message {
	mi := &file_indexing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapedItem.ProtoReflect.Descriptor instead.
func (*ScrapedItem) Descriptor() ([]byte, []int) {
	return file_indexing_proto_rawDescGZIP(), []int{0}
}

func (x *ScrapedItem) GetPageUrl() string {
	if x != nil {
		return x.PageUrl
	}
	return ""
}

func (x *ScrapedItem) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *ScrapedItem) GetMediaType() MediaType {
	if x != nil {
		return x.MediaType
	}
	return MediaType_UNKNOWN
}

type ProcessScrapedItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ScrapedItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessScrapedItemsRequest) Reset() {
	*x = ProcessScrapedItemsRequest{}
	mi := &file_indexing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessScrapedItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessScrapedItemsRequest) ProtoMessage() {}

func (x *ProcessScrapedItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessScrapedItemsRequest.ProtoReflect.Descriptor instead.
func (*ProcessScrapedItemsRequest) Descriptor() ([]byte, []int) {
	return file_indexing_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessScrapedItemsRequest) GetItems() []*ScrapedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ProcessScrapedItemsRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type ProcessScrapedItemsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ItemsReceived  int32                  `protobuf:"varint,1,opt,name=items_received,json=itemsReceived,proto3" json:"items_received,omitempty"`
	ItemsProcessed int32                  `protobuf:"varint,2,opt,name=items_processed,json=itemsProcessed,proto3" json:"items_processed,omitempty"`
	ItemsFailed    int32                  `protobuf:"varint,3,opt,name=items_failed,json=itemsFailed,proto3" json:"items_failed,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessScrapedItemsResponse) Reset() {
	*x = ProcessScrapedItemsResponse{}
	mi := &file_indexing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessScrapedItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessScrapedItemsResponse) ProtoMessage() {}

func (x *ProcessScrapedItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessScrapedItemsResponse.ProtoReflect.Descriptor instead.
func (*ProcessScrapedItemsResponse) Descriptor() ([]byte, []int) {
	return file_indexing_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessScrapedItemsResponse) GetItemsReceived() int32 {
	if x != nil {
		return x.ItemsReceived
	}
	return 0
}

func (x *ProcessScrapedItemsResponse) GetItemsProcessed() int32 {
	if x != nil {
		return x.ItemsProcessed
	}
	return 0
}

func (x *ProcessScrapedItemsResponse) GetItemsFailed() int32 {
	if x != nil {
		return x.ItemsFailed
	}
	return 0
}

func (x *ProcessScrapedItemsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_indexing_proto protoreflect.FileDescriptor

const file_indexing_proto_rawDesc = "" +
	"\n" +
	"\x0eindexing.proto\x12\bindexing\"y\n" +
	"\vScrapedItem\x12\x19\n" +
	"\bpage_url\x18\x01 \x01(\tR\apageUrl\x12\x1b\n" +
	"\tmedia_url\x18\x02 \x01(\tR\bmediaUrl\x122\n" +
	"\n" +
	"media_type\x18\x03 \x01(\x0e2\x13.indexing.MediaTypeR\tmediaType\"`\n" +
	"\x1aProcessScrapedItemsRequest\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.indexing.ScrapedItemR\x05items\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\"\xaa\x01\n" +
	"\x1bProcessScrapedItemsResponse\x12%\n" +
	"\x0eitems_received\x18\x01 \x01(\x05R\ritemsReceived\x12'\n" +
	"\x0fitems_processed\x18\x02 \x01(\x05R\x0eitemsProcessed\x12!\n" +
	"\fitems_failed\x18\x03 \x01(\x05R\vitemsFailed\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage*.\n" +
	"\tMediaType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05IMAGE\x10\x01\x12\t\n" +
	"\x05AUDIO\x10\x022u\n" +
	"\x0fIndexingService\x12b\n" +
	"\x13ProcessScrapedItems\x12$.indexing.ProcessScrapedItemsRequest\x1a%.indexing.ProcessScrapedItemsResponseB-Z+YOUR_MODULE_PATH/internal/client/indexingpbb\x06proto3"

var (
	file_indexing_proto_rawDescOnce sync.Once
	file_indexing_proto_rawDescData []byte
)

func file_indexing_proto_rawDescGZIP() []byte {
	file_indexing_proto_rawDescOnce.Do(func() {
		file_indexing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_indexing_proto_rawDesc), len(file_indexing_proto_rawDesc)))
	})
	return file_indexing_proto_rawDescData
}

var file_indexing_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_indexing_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_indexing_proto_goTypes = []any{
	(MediaType)(0),                      // 0: indexing.MediaType
	(*ScrapedItem)(nil),                 // 1: indexing.ScrapedItem
	(*ProcessScrapedItemsRequest)(nil),  // 2: indexing.ProcessScrapedItemsRequest
	(*ProcessScrapedItemsResponse)(nil), // 3: indexing.ProcessScrapedItemsResponse
}
var file_indexing_proto_depIdxs = []int32{
	0, // 0: indexing.ScrapedItem.media_type:type_name -> indexing.MediaType
	1, // 1: indexing.ProcessScrapedItemsRequest.items:type_name -> indexing.ScrapedItem
	2, // 2: indexing.IndexingService.ProcessScrapedItems:input_type -> indexing.ProcessScrapedItemsRequest
	3, // 3: indexing.IndexingService.ProcessScrapedItems:output_type -> indexing.ProcessScrapedItemsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_indexing_proto_init() }
func file_indexing_proto_init() {
	if File_indexing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_indexing_proto_rawDesc), len(file_indexing_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_indexing_proto_goTypes,
		DependencyIndexes: file_indexing_proto_depIdxs,
		EnumInfos:         file_indexing_proto_enumTypes,
		MessageInfos:      file_indexing_proto_msgTypes,
	}.Build()
	File_indexing_proto = out.File
	file_indexing_proto_goTypes = nil
	file_indexing_proto_depIdxs = nil
}
