// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.1
// source: indexing.proto

package indexingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IndexingService_ProcessScrapedItems_FullMethodName = "/indexing.IndexingService/ProcessScrapedItems"
)

// IndexingServiceClient is the client API for IndexingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IndexingServiceClient interface {
	ProcessScrapedItems(ctx context.Context, in *ProcessScrapedItemsRequest, opts ...grpc.CallOption) (*ProcessScrapedItemsResponse, error)
}

type indexingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIndexingServiceClient(cc grpc.ClientConnInterface) IndexingServiceClient {
	return &indexingServiceClient{cc}
}

func (c *indexingServiceClient) ProcessScrapedItems(ctx context.Context, in *ProcessScrapedItemsRequest, opts ...grpc.CallOption) (*ProcessScrapedItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessScrapedItemsResponse)
	err := c.cc.Invoke(ctx, IndexingService_ProcessScrapedItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IndexingServiceServer is the server API for IndexingService service.
// All implementations must embed UnimplementedIndexingServiceServer
// for forward compatibility.
type IndexingServiceServer interface {
	ProcessScrapedItems(context.Context, *ProcessScrapedItemsRequest) (*ProcessScrapedItemsResponse, error)
	mustEmbedUnimplementedIndexingServiceServer()
}

// UnimplementedIndexingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIndexingServiceServer struct{}

func (UnimplementedIndexingServiceServer) ProcessScrapedItems(context.Context, *ProcessScrapedItemsRequest) (*ProcessScrapedItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessScrapedItems not implemented")
}
func (UnimplementedIndexingServiceServer) mustEmbedUnimplementedIndexingServiceServer() {}
func (UnimplementedIndexingServiceServer) testEmbeddedByValue()                         {}

// UnsafeIndexingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IndexingServiceServer will
// result in compilation errors.
type UnsafeIndexingServiceServer interface {
	mustEmbedUnimplementedIndexingServiceServer()
}

func RegisterIndexingServiceServer(s grpc.ServiceRegistrar, srv IndexingServiceServer) {
	// If the following call pancis, it indicates UnimplementedIndexingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IndexingService_ServiceDesc, srv)
}

func _IndexingService_ProcessScrapedItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessScrapedItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexingServiceServer).ProcessScrapedItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexingService_ProcessScrapedItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexingServiceServer).ProcessScrapedItems(ctx, req.(*ProcessScrapedItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IndexingService_ServiceDesc is the grpc.ServiceDesc for IndexingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IndexingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "indexing.IndexingService",
	HandlerType: (*IndexingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessScrapedItems",
			Handler:    _IndexingService_ProcessScrapedItems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "indexing.proto",
}
