// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: feature.proto

package featurepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaType int32

const (
	MediaType_UNKNOWN MediaType = 0
	MediaType_IMAGE   MediaType = 1
	MediaType_AUDIO   MediaType = 2
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "UNKNOWN",
		1: "IMAGE",
		2: "AUDIO",
	}
	MediaType_value = map[string]int32{
		"UNKNOWN": 0,
		"IMAGE":   1,
		"AUDIO":   2,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_feature_proto_enumTypes[0].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_feature_proto_enumTypes[0]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_feature_proto_rawDescGZIP(), []int{0}
}

type Status int32

const (
	Status_STATUS_UNKNOWN          Status = 0
	Status_SUCCESS                 Status = 1
	Status_FAILED_DOWNLOAD         Status = 2
	Status_FAILED_PROCESSING       Status = 3
	Status_FAILED_UNSUPPORTED_TYPE Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "SUCCESS",
		2: "FAILED_DOWNLOAD",
		3: "FAILED_PROCESSING",
		4: "FAILED_UNSUPPORTED_TYPE",
	}
	Status_value = map[string]int32{
		"STATUS_UNKNOWN":          0,
		"SUCCESS":                 1,
		"FAILED_DOWNLOAD":         2,
		"FAILED_PROCESSING":       3,
		"FAILED_UNSUPPORTED_TYPE": 4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_feature_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_feature_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_feature_proto_rawDescGZIP(), []int{1}
}

type UrlItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaUrl      string                 `protobuf:"bytes,1,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	Type          MediaType              `protobuf:"varint,2,opt,name=type,proto3,enum=feature.MediaType" json:"type,omitempty"`
	PageUrl       string                 `protobuf:"bytes,3,opt,name=page_url,json=pageUrl,proto3" json:"page_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UrlItem) Reset() {
	*x = UrlItem{}
	mi := &file_feature_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrlItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlItem) ProtoMessage() {}

func (x *UrlItem) ProtoReflect() protoreflect.Message {
	mi := &file_feature_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlItem.ProtoReflect.Descriptor instead.
func (*UrlItem) Descriptor() ([]byte, []int) {
	return file_feature_proto_rawDescGZIP(), []int{0}
}

func (x *UrlItem) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *UrlItem) GetType() MediaType {
	if x != nil {
		return x.Type
	}
	return MediaType_UNKNOWN
}

func (x *UrlItem) GetPageUrl() string {
	if x != nil {
		return x.PageUrl
	}
	return ""
}

type ProcessUrlsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Items          []*UrlItem             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	ApplyDenoising bool                   `protobuf:"varint,2,opt,name=apply_denoising,json=applyDenoising,proto3" json:"apply_denoising,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessUrlsRequest) Reset() {
	*x = ProcessUrlsRequest{}
	mi := &file_feature_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessUrlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessUrlsRequest) ProtoMessage() {}

func (x *ProcessUrlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feature_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessUrlsRequest.ProtoReflect.Descriptor instead.
func (*ProcessUrlsRequest) Descriptor() ([]byte, []int) {
	return file_feature_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessUrlsRequest) GetItems() []*UrlItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ProcessUrlsRequest) GetApplyDenoising() bool {
	if x != nil {
		return x.ApplyDenoising
	}
	return false
}

type FeatureResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaUrl      string                 `protobuf:"bytes,1,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=feature.Status" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	FeatureVector []byte                 `protobuf:"bytes,4,opt,name=feature_vector,json=featureVector,proto3" json:"feature_vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureResult) Reset() {
	*x = FeatureResult{}
	mi := &file_feature_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureResult) ProtoMessage() {}

func (x *FeatureResult) ProtoReflect() protoreflect.Message {
	mi := &file_feature_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureResult.ProtoReflect.Descriptor instead.
func (*FeatureResult) Descriptor() ([]byte, []int) {
	return file_feature_proto_rawDescGZIP(), []int{2}
}

func (x *FeatureResult) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *FeatureResult) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOWN
}

func (x *FeatureResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *FeatureResult) GetFeatureVector() []byte {
	if x != nil {
		return x.FeatureVector
	}
	return nil
}

type ProcessUrlsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*FeatureResult       `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessUrlsResponse) Reset() {
	*x = ProcessUrlsResponse{}
	mi := &file_feature_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessUrlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessUrlsResponse) ProtoMessage() {}

func (x *ProcessUrlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feature_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessUrlsResponse.ProtoReflect.Descriptor instead.
func (*ProcessUrlsResponse) Descriptor() ([]byte, []int) {
	return file_feature_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessUrlsResponse) GetResults() []*FeatureResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_feature_proto protoreflect.FileDescriptor

const file_feature_proto_rawDesc = "" +
	"\n" +
	"\rfeature.proto\x12\afeature\"i\n" +
	"\aUrlItem\x12\x1b\n" +
	"\tmedia_url\x18\x01 \x01(\tR\bmediaUrl\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.feature.MediaTypeR\x04type\x12\x19\n" +
	"\bpage_url\x18\x03 \x01(\tR\apageUrl\"e\n" +
	"\x12ProcessUrlsRequest\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.feature.UrlItemR\x05items\x12'\n" +
	"\x0fapply_denoising\x18\x02 \x01(\bR\x0eapplyDenoising\"\xa1\x01\n" +
	"\rFeatureResult\x12\x1b\n" +
	"\tmedia_url\x18\x01 \x01(\tR\bmediaUrl\x12'\n" +
	"\x06status\x18\x02 \x01(\x0e2\x0f.feature.StatusR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0efeature_vector\x18\x04 \x01(\fR\rfeatureVector\"G\n" +
	"\x13ProcessUrlsResponse\x120\n" +
	"\aresults\x18\x01 \x03(\v2\x16.feature.FeatureResultR\aresults*.\n" +
	"\tMediaType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05IMAGE\x10\x01\x12\t\n" +
	"\x05AUDIO\x10\x02*r\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\x13\n" +
	"\x0fFAILED_DOWNLOAD\x10\x02\x12\x15\n" +
	"\x11FAILED_PROCESSING\x10\x03\x12\x1b\n" +
	"\x17FAILED_UNSUPPORTED_TYPE\x10\x042Z\n" +
	"\x0eFeatureService\x12H\n" +
	"\vProcessUrls\x12\x1b.feature.ProcessUrlsRequest\x1a\x1c.feature.ProcessUrlsResponseBRZPgithub.com/Mahmoud-T-Almetwally/Image-Audio-Web-Search/internal/client/featurepbb\x06proto3"

var (
	file_feature_proto_rawDescOnce sync.Once
	file_feature_proto_rawDescData []byte
)

func file_feature_proto_rawDescGZIP() []byte {
	file_feature_proto_rawDescOnce.Do(func() {
		file_feature_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feature_proto_rawDesc), len(file_feature_proto_rawDesc)))
	})
	return file_feature_proto_rawDescData
}

var file_feature_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_feature_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_feature_proto_goTypes = []any{
	(MediaType)(0),              // 0: feature.MediaType
	(Status)(0),                 // 1: feature.Status
	(*UrlItem)(nil),             // 2: feature.UrlItem
	(*ProcessUrlsRequest)(nil),  // 3: feature.ProcessUrlsRequest
	(*FeatureResult)(nil),       // 4: feature.FeatureResult
	(*ProcessUrlsResponse)(nil), // 5: feature.ProcessUrlsResponse
}
var file_feature_proto_depIdxs = []int32{
	0, // 0: feature.UrlItem.type:type_name -> feature.MediaType
	2, // 1: feature.ProcessUrlsRequest.items:type_name -> feature.UrlItem
	1, // 2: feature.FeatureResult.status:type_name -> feature.Status
	4, // 3: feature.ProcessUrlsResponse.results:type_name -> feature.FeatureResult
	3, // 4: feature.FeatureService.ProcessUrls:input_type -> feature.ProcessUrlsRequest
	5, // 5: feature.FeatureService.ProcessUrls:output_type -> feature.ProcessUrlsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_feature_proto_init() }
func file_feature_proto_init() {
	if File_feature_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feature_proto_rawDesc), len(file_feature_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feature_proto_goTypes,
		DependencyIndexes: file_feature_proto_depIdxs,
		EnumInfos:         file_feature_proto_enumTypes,
		MessageInfos:      file_feature_proto_msgTypes,
	}.Build()
	File_feature_proto = out.File
	file_feature_proto_goTypes = nil
	file_feature_proto_depIdxs = nil
}
